## Python Crash Course Review (Part II)

### 1. Lists and other sequences

In [1]:
from math import pi
[] # empty list
a = [-7, 1., 'you', 3]   # list (mutable)
B = [[1, 2, 3], pi, 2]   # nested list
c = (1,2)                # tuple (immutable)
d = 1,2                  # tuple 
e = ['numerical', 'differential', 'equations']   # string

> <font color='purple'> Change the first element of a to a[0] = 10 and try to change the first element of c to c[0]=10.</font> 

In [2]:
print(B[0])

[1, 2, 3]


In [3]:
print(a, c, d)
print('a+B: ',a+B)         # concatenating two lists  

[-7, 1.0, 'you', 3] (1, 2) (1, 2)
a+B:  [-7, 1.0, 'you', 3, [1, 2, 3], 3.141592653589793, 2]


> <font color='purple'> Write two lists i=[1,2,3], j=[5] and concatenate i and j.</font> 

In [4]:
i=[1,2,3] 
j=[5]
print("i=\n",i,"\n", "j=\n",j)
print(i+j)

i=
 [1, 2, 3] 
 j=
 [5]
[1, 2, 3, 5]


#### 1.a) Basics Indexing/Slicing (in Python list/array indices start with 0, in Matlab with 1)

In [5]:
print(e[0][0])  
print(len(e))
print(B, "\n", B[0][2])  # indexing a nested list

n
3
[[1, 2, 3], 3.141592653589793, 2] 
 3


In [6]:
v = list(range(10))
print(v,"\n", v[-1],"\n", v[0:2],"\n", v[2:],"\n")      

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 9 
 [0, 1] 
 [2, 3, 4, 5, 6, 7, 8, 9] 



> <font color='purple'> Create a new list n = [0,3,6,9] from v by specifying a suitable set of indices n=v[start:stop:step].</font>   
> [https://stackoverflow.com/questions/509211/understanding-slice-notation](https://stackoverflow.com/questions/509211/understanding-slice-notation)

#### 1.b) Indexing n dimensional arrays

In [7]:
import numpy as np           # vectors
v = np.array([1,2,3,4,5])
i = [0,2,4]
print(v[i])             

[1 3 5]


In [8]:
import numpy as np                  # 2d-arrays (matrices)
A = np.array([[0,1,2],[3,4,5]])
print("A =\n",A)
print(A.shape)

A =
 [[0 1 2]
 [3 4 5]]
(2, 3)


In [9]:
print(A[...,0])
print(A[:,0])
print(A[:2,0])
print(A[-2:,0])
print(A[0:,0])

[0 3]
[0 3]
[0 3]
[0 3]
[0 3]


> <font color='purple'>Find 3 (or 5) ways to create the array $A[0,:]=[0,1,2]$ from A. </font>    
> [https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html)      .

#### 1.c Assemble an nd-array from nested lists of blocks

In [10]:
B = np.array([[6,7,8],
              [9,10,11]])
C = np.block([[A,B],
              [B,A]])
print(C)
C = np.block([  [A,A],
                [B,B]    ])
print("C =\n", C)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]
 [ 6  7  8  0  1  2]
 [ 9 10 11  3  4  5]]
C =
 [[ 0  1  2  0  1  2]
 [ 3  4  5  3  4  5]
 [ 6  7  8  6  7  8]
 [ 9 10 11  9 10 11]]


#### 1.c Extract a submatrix using indexing arrays

In [11]:
D = C[:2,:2]                        # extract upper left 2-by-2 block matrix
print(D)
i = np.array([0,1])                 # ...using numpy.ix_ function 
j = np.array([0,1])                  
E = np.array(C[np.ix_(i, j)])
print(E)

[[0 1]
 [3 4]]
[[0 1]
 [3 4]]


In [12]:
F = np.array([C[...,0],C[...,2]])       # extract 1st & 3rd column 
G = np.array([C[:,0],C[:,2]])           # ...into nd-array with 2 rows
print("F =\n",F,"\nG =\n", G.T)         # print transposed                    

F =
 [[ 0  3  6  9]
 [ 2  5  8 11]] 
G =
 [[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [13]:
v = np.array([1,2,3]).T
print(v)

[1 2 3]


> <font color='purple'> Find the 'scipy.docs.org' reference describing the 'numpy.ix_' function. </font>

### 2. Functions

#### 2.a) Defining a function with two arguments which returns $f(x,y)=\sqrt{x}+\text{e}^y$. (Remember code block indentation)

In [14]:
def f(x, y):
    from math import sqrt, exp     # 4 empty spaces
    return sqrt(x)+exp(y)

In [15]:
print(f(0,0), f(1,1))

1.0 3.718281828459045


#### 2.b) Always add a docstring to your python program.

In [16]:
def g(x=0, y=None):                # initialized parameter
    ''' demo function '''          # docstring 
    from math import sqrt, exp
    z = 2                          # local variable z
    return z, sqrt(x)+exp(y)

#### 2.c) What is the scope of a variable (local/global)? 

In [17]:
z = 4                              # global variable z
print(g(0,0))
print(z)

(2, 1.0)
4


> <font color='purple'> Uncomment z=2 in the function g. </font>

In [18]:
help(g)

Help on function g in module __main__:

g(x=0, y=None)
    demo function



#### 2.d) A python script file that calls its function, main scope  

> [https://docs.python.org/3/library/__main__.html](https://docs.python.org/3/library/__main__.html)

In [19]:
def greet():
    print("Hello World")
    
if __name__ == "__main__":
    greet()     

Hello World


In [20]:
''' this is our first python file name date lu decomposition'''
import numpy as np   

def main(): 
    L = np.array([[1,0,0],[-2,1,0],[4,5,1]])
    b = np.array([18,-3,231])
   
    y = forward(L,b) 
    print(y)
    print(L.shape[0])

def forward(L,b):
    n = L.shape[0]
    y = np.zeros(n)
    for k in range(n):
        y[k]=b[k]
        for j in range(k):
            y[k]=y[k]-L[k,j]*y[j] 
            
    return y

#def backward(U,y):
    
    

if __name__ == "__main__":
    main()     

[18. 33. -6.]
3


In [21]:
n=3
for k in range(n-1,-1,-1):
    print(k)
    for j in range(k+1,n):
        print(k)

2
1
1
0
0
0


In [22]:
for i in range(3):
    print(i)

0
1
2


> replace greet() by main()  to get a nice template for your homework files  
> [https://stackoverflow.com/questions/419163/what-does-if-name-main-do](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

### 3. What are PEPs and some more in-depth tutorials

> The [Zen of Python](https://www.python.org/dev/peps/pep-0020/) and [Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#other-recommendations)

> [https://docs.python-guide.org/](https://docs.python-guide.org/)

> [https://docs.python-guide.org/intro/learning/](https://docs.python-guide.org/intro/learning/)

> [http://www.davekuhlman.org/python_book_01.html](http://www.davekuhlman.org/python_book_01.html)