## Polynomial interpolation

In [1]:
### Plotting our example

In [2]:
import numpy as np

p = np.poly1d([1,0,2])
print(p)

t = np.array(np.linspace(-1.1,1.1, 100) )
y = p(t)
#print(y)

#%matplotlib inline                    
#import pylab as pl

#pl.plot(t, y)
#pl.show()

   2
1 x + 2


In [3]:
### Vandermonde matrix

How to generate V from  $ x = [x_1,x_2,...,x_n+1]^𝑇 $

and other functions for polynomial interpolation

https://docs.scipy.org/doc/numpy/user/

https://docs.scipy.org/doc/numpy/reference/routines.polynomials.polynomial.html

In [4]:
import numpy as np

x = np.array([-1,0,1])
V = np.polynomial.polynomial.polyvander(x,2)
print(V)

[[ 1. -1.  1.]
 [ 1.  0.  0.]
 [ 1.  1.  1.]]


In [5]:
## Lagrange interpolation, Lagrange basis polynomials

In [6]:
import numpy as np

x = np.array([-1,0,1])
f = np.array([3,2,3])
#f = 2 +x^2
print(x)
print(f)

def Lagrange_polynomial(t=0.0):
    ''' p(t) = sum_[k=1]^n f_k * L_k(t)
        L_k(t) = prod_[j=1],j!=k]=1^n (t - x_j)/(x_k - x_j) '''
    n = len(x)
    Lagrange = np.ones(n)
    polynomial = 0.0
    
    for k in range(n):
        i_not_k = [j for j in list(range(n)) if j !=k]
        for e in i_not_k:
            Lagrange[k] = Lagrange[k]*(t-x[e])/(x[k]-x[e])     
        polynomial = polynomial + f[k]*Lagrange[k]
        
    return polynomial


if __name__ == "__main__":
    
    z = np.linspace(x[0],x[-1],100)
    y = np.zeros(100)
    
    for i,t in enumerate(z):
        y[i] = Lagrange_polynomial(t)
        
    print(y[0],y[50],y[-1])

[-1  0  1]
[3 2 3]
3.0 2.0001020304050607 3.0


In [7]:
#### Explore the interpolation library

In [8]:
#import scipy as sp
#poly = sp.interpolate.lagrange(x, f)

#from sp.interpolate import lagrange
#poly = lagrange(x, f)

#print(poly)

In [9]:
### Newton interpolation polynomial, developing the algorithm to computed divided differences [WIP]

In [10]:
import numpy as np

np1 = len(x) 
dd = np.zeros((np1,np1))
dd[:,0] = f
for j in range(1,np1):
    for k in range(np1-j):
        #print(j,k)
        dd[k,j] = (dd[k+1,j-1]-dd[k,j-1])/(x[k+j] -x[k])
        
print(dd)

[[ 3. -1.  1.]
 [ 2.  1.  0.]
 [ 3.  0.  0.]]
